clang-16 : Fix -Wint-conversion
Caused by:
../kernel/fork.c:1346:25: error: incompatible pointer to integer conversion passing 'char[6]' to parameter of type 'char' [-Wint-conversion]
        seq_put_decimal_ull(m, "Pid:\t", pid_nr_ns(pid, ns));
                               ^~~~~~~~
../include/linux/seq_file.h:120:57: note: passing argument to parameter 'delimiter' here
void seq_put_decimal_ull(struct seq_file *m, const char delimiter,
                                                        ^
1 error generated.

Signed-off-by: Aditya Eka Pranata <aepranata@gmail.com>